export const SIGNUP_ACTION = '[actions] signup user';
export const SET_USER_TOKEN_DATA_MUTATION = '[mutations] set user token';
export const LOADING_SPINNER_SHOW_MUTATION = '[mutations] show loading spinner';
export const LOGIN_ACTION = '[actions] login user';
export const GET_USER_TOKEN_GETTER = '[getters] auth user token';
export const IS_USER_AUTHENTICATED_GETTER = '[getters] is user authenticated';
export const LOGOUT_ACTION = '[actions] logout user';
export const AUTH_ACTION = '[actions] do user auth';
export const AUTO_LOGIN_ACTION = '[actions] auth auto login'
export const AUTO_LOGOUT_ACTION = '[actions] auto logout'
